### PR TITLE
[labs/react] Remove custom children type and include our own copy of `PropsWithoutRef` for usage with `preact/compat`

### LINKED ISSUE #4169: [labs/react] Created component type is incompatible in Preact with typescript >=5.1
### Which package(s) are affected?

React (@lit-labs/react)

### Description

May be related to https://www.typescriptlang.org/docs/handbook/release-notes/typescript-5-1.html#decoupled-type-checking-between-jsx-elements-and-jsx-tag-types

Using wrapped component in Preact yields:
```
'ElementA' cannot be used as a JSX component.
  Its type 'ReactWebComponent<ElementA, { onAChanged: EventName<CustomEvent<unknown>>; }>' is not a valid JSX element type.
    Type 'ForwardRefExoticComponent<Omit<HTMLAttributes<ElementA>, "children" | "onAChanged"> & EventListeners<{ onAChanged: EventName<CustomEvent<unknown>>; }> & { ...; } & Partial<...> & RefAttributes<...>>' is not assignable to type 'FunctionComponent<any>'.
      Type 'ReactNode' is not assignable to type 'VNode<any>'.
        Type 'string' is not assignable to type 'VNode<any>'.ts(2786)
```

We may need to ditch `ForwardRefExoticComponent` and just type the component in a more generic way.

### Reproduction

Bump the version of typescript in the examples/preact in the monorepo.

### Workaround

downgrade TS to ~5.0

### Is this a regression?

Yes. This used to work, but now it doesn't.

### Affected versions

2.0.2

### Browser/OS/Node environment

N/A

### PR DESCRIPTION
**Pull request by augustjk**
Fixes #4169, #4138 

Instead of trying to figure out React-Preact compatible types ourselves like the franken-child type, it would be better for us to defer to `preact/compat` typings that provide their versions of React types.

Due to https://github.com/preactjs/preact/issues/4124, we need to use our own copy of `PropsWithoutRef` type for proper type checking to occur with `preact/compat`.

This will also ensure we don't mix React and Preact types for users of TS >= 5.1 where the types become further incompatible.

Tested with our `examples/preact` project configured now to use `preact/compat`. I have also tested this after manually updating the typescript dependency version for the example project.

### CODE REVIEW

File: packages/labs/react/src/create-component.ts [hunk 1]
```diff
@@ -31,6 +31,18 @@ export type WebComponentProps<I extends HTMLElement> = React.DetailedHTMLProps<
...
+// included in preact/compat yet.
+// See: https://github.com/preactjs/preact/issues/4124
+/** Ensures that the props do not include ref at all */
+type PropsWithoutRef<P> =
+  // Omit would not be sufficient for this. We'd like to avoid unnecessary mapping and need a distributive conditional to support unions.
+  // see: https://www.typescriptlang.org/docs/handbook/2/conditional-types.html#distributive-conditional-types
+  // https://github.com/Microsoft/TypeScript/issues/28339
+  // eslint-disable-next-line @typescript-eslint/no-explicit-any
+  P extends any ? ('ref' extends keyof P ? Omit<P, 'ref'> : P) : P;
+
```
Comment (AndrewJakubowicz) [inline packages/labs/react/src/create-component.ts:45]: spoke offline – would be nice to isolate this in a separate file and include the license.

**Review by AndrewJakubowicz — COMMENTED** [review]
Fantastic investigating and solution!

File: packages/labs/react/src/create-component.ts (hunk 1 above)
Comment (augustjk) [reply packages/labs/react/src/create-component.ts]: Thank you, I have split out `PropsWithoutRef` into its own file and included all license and attributions there.

File: packages/labs/react/package.json [hunk 2]
```diff
@@ -80,7 +81,7 @@
       ]
     },
     "build:ts:types": {
-      "command": "treemirror development . \"**/*.d.ts{,.map}\" \"!development/test\"",
+      "command": "treemirror development . \"**/*.d.ts{,.map}\" \"!test\"",
```
Comment (AndrewJakubowicz) [inline packages/labs/react/package.json:84]: Is this change expected?

**Review by AndrewJakubowicz — APPROVED** [review]
Nice!

File: packages/labs/react/package.json (hunk 2 above)
Comment (augustjk) [reply packages/labs/react/package.json:84]: Yes intended! It was incorrect when I added this a while back. Since we already set `development` as the source dir in the first argument, the glob starts relative to that. It was no harm that it wasn't working, just unnecessarily copying extra test files.

File: packages/labs/react/rollup.config.js [hunk 3]
```diff
@@ -9,6 +9,11 @@ import {createRequire} from 'module';
 
 export default litProdConfig({
   packageName: createRequire(import.meta.url)('./package.json').name,
-  entryPoints: ['index', 'create-component', 'use-controller'],
+  entryPoints: [
+    'index',
+    'create-component',
+    'use-controller',
+    'props-without-ref',
```
Comment (justinfagnani) [inline packages/labs/react/rollup.config.js:16]: Should this be listed as an entrypoint?

**Review by justinfagnani — APPROVED** [review]
LGTM, with a question on if the new file needs to be in the rollup config entrypoints.

We're not publishing in exports, so it doesn't matter _that_ much, but we are putting the file in the top-level, so someone not using package exports could import this file.

File: packages/labs/react/rollup.config.js (hunk 3 above)
Comment (rictic) [reply packages/labs/react/rollup.config.js:16]: +1. We should keep exports and entrypoints in sync.

Comment (AndrewJakubowicz) [reply packages/labs/react/rollup.config.js]: I reverted the entrypoints so it doesn't contain the new file "props-without-ref"

**Comment by augustjk** [comment]
> LGTM, with a question on if the new file needs to be in the rollup config entrypoints.
> 
> We're not publishing in exports, so it doesn't matter _that_ much, but we are putting the file in the top-level, so someone not using package exports could import this file.

It's included as rollup config to generate the js and js.map files but it is type only. I wasn't sure if the type import would resolve with just the d.ts file present. It's an empty file so i think it's no harm to have it emit and included in the package without any package export mapping.

**Comment by justinfagnani** [comment]
> It's included as rollup config to generate the js and js.map files but it is type only.

Ah. In that case I'd like to use `import type` to note that it will elide the import completely, and then skip the .js files. But...

Can we just inline the type into `create-component.ts`? We can still indicate that we copied it from DefinitelyTyped with a link to the file. It's only ~60 chars or so.

**Comment by AndrewJakubowicz** [comment]
> Can we just inline the type into create-component.ts?

This is my fault since I asked to keep the license with the copied source code. By copying the code & license into a separate file it's easier to delete in the future when the type is included in preact's compatibility types.

+1 to `import type`

**Comment by justinfagnani** [comment]
Since it's a one-liner, can we just inline something?

Here's a version that's not a copy that distributes `Omit`:

```ts
type DistributiveOmit<T, K extends string | number | symbol> = T extends any ? Omit<T, K> : T;

// usage
export type OmitRef<T> = DistributiveOmit<T, 'ref'>;
```

The only difference is that in editors if you hover over the type you'll always see the `OmitRef<..., 'ref'>` even if the original type didn't have ref in it. I don't think this is bad, considering the only place we use the type is in a complex type anyway.

**Comment by AndrewJakubowicz** [comment]
Applied code review feedback. @justinfagnani, I needed to tweak the type slightly more to get the generic distributive omit to type check.

#### Test plan

I manually tested this change against examples/preact with TypeScript 5.2 and the error no longer occurs.
Requesting re-review from @justinfagnani  or @rictic .

**Review by justinfagnani — APPROVED** [review]
thanks!
