### PR TITLE
Bind this to custom attribute converter methods

### LINKED ISSUE #3108: [reactive-element] `ComplexAttributeConverter`, `this` is `undefined` in `fromAttribute` method
### Which package(s) are affected?

Lit Core (lit / lit-html / lit-element / reactive-element)

### Description

I try to implement a `ComplexAttributeConverter` whereas I want to pass a default value to it that should be used as a fallback in the `fromAttribute` method. Unfortunately `this` is undefined in this method. I debugged why this is the case and it seems the function is not called via [apply()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/apply) which results in `this` being undefined.

I wonder why is this the case. Can we fix this?

### Reproduction

- Implement converter that allows passing a default value via constructor

``` ts
import { ComplexAttributeConverter } from "lit-element";

export class IntegerAttributeConverter implements ComplexAttributeConverter<Number> {
  private _defaultValue: Number;

  constructor(defaultValue: Number) {
    this._defaultValue = defaultValue;
  }

  toAttribute(value: Number, _type?: unknown): unknown {
    return `${value}`;
  }

  fromAttribute(value: string|null, _type?: unknown): Number {
    if (value) {
      const result = Number.parseInt(value, 10);

      if (isNaN(result))
        return this._defaultValue;
      else
        return result;
    }
    else
      return this._defaultValue;
  }
}
```

- Use converter in a property decoration

``` ts
const defaultPageSize: number = 10;

@property({ type: Number, converter: new IntegerAttributeConverter(defaultPageSize) })
  pageSize: number = defaultPageSize;
``` 

### Workaround

Implement the converter as a callback function

``` ts
const defaultPageSize: number = 10;

@property({
  type: Number,
  converter: (attributeValue: string | null, _type?: unknown): Number => {
    // same code as IntegerAttributeConverter.fromAttribute with access to defaultPageSize
  })
pageSize: number = defaultPageSize;
```

### Is this a regression?

No or unsure. This never worked, or I haven't tried before.

### Affected versions

2.0.2

### Browser/OS/Node environment

Doesn't matter

### PR DESCRIPTION
**Pull request by nebarf**
Fixes #3108

### CODE REVIEW

File: packages/reactive-element/src/reactive-element.ts [hunk 1]
```diff
@@ -1069,9 +1069,11 @@ export abstract class ReactiveElement
       this.constructor as typeof ReactiveElement
     ).__attributeNameForProperty(name, options);
     if (attr !== undefined && options.reflect === true) {
+      const converter = options.converter;
       const toAttribute =
-        (options.converter as ComplexAttributeConverter)?.toAttribute ??
-        defaultConverter.toAttribute;
+        (converter as ComplexAttributeConverter)?.toAttribute?.bind(
+          converter
+        ) ?? defaultConverter.toAttribute;
```
Comment (justinfagnani) [inline packages/reactive-element/src/reactive-element.ts:1076]: If it wouldn't be a breaking change, it'd be nice and simple to just do:

```ts
const attrValue = (converter ?? defaultConverter).toAttribute?.(value, options.type);
```

but this would change the behavior of the case where there's a converter but with no `toAttribute`. cc @sorvell

**Review by justinfagnani — CHANGES_REQUESTED** [review]
Thanks for the fix @nebarf !

I made some comments around creating fewer short-lived function objects due to `Function.bind()` when setting properties/attributes.

A bigger change that we should consider outside of this fix (I think) would be to do the `toAttribute`/`fromAttribute` determination in `createProperty()` so it's done once per class, not on every property set. cc @sorvell

File: packages/reactive-element/src/reactive-element.ts (hunk 1 above)
Comment (nebarf) [reply packages/reactive-element/src/reactive-element.ts:1076]: It would be a breaking change in case a converter is provided as function. Quoting from docs:

> If converter is a **function**, it is used in place of **fromAttribute**

File: packages/reactive-element/src/reactive-element.ts [hunk 2]
```diff
@@ -1069,9 +1069,11 @@ export abstract class ReactiveElement
       this.constructor as typeof ReactiveElement
     ).__attributeNameForProperty(name, options);
     if (attr !== undefined && options.reflect === true) {
+      const converter = options.converter;
       const toAttribute =
-        (options.converter as ComplexAttributeConverter)?.toAttribute ??
-        defaultConverter.toAttribute;
+        (converter as ComplexAttributeConverter)?.toAttribute?.bind(
```
[the remark this answers is not in the document]
Comment (nebarf) [reply packages/reactive-element/src/reactive-element.ts:1074]: Good hint! Thanks

File: .changeset/old-tables-own.md [hunk 3]
```diff
@@ -0,0 +1,5 @@
+---
+'@lit/reactive-element': patch
+---
+
+Bind this to custom attribute converter methods
```
Comment (augustjk) [inline .changeset/old-tables-own.md:5]: We'll want to bump `lit` along with `reactive-element` and backticks around `this` so it's more apparent that it's referring to the keyword.
```suggestion
---
'@lit/reactive-element': patch
'lit': patch
---

Bind `this` to custom attribute converter methods
```

File: packages/reactive-element/src/reactive-element.ts [hunk 4]
```diff
@@ -1117,17 +1119,19 @@ export abstract class ReactiveElement
...
+          ? options.converter
+          : defaultConverter;
       // mark state reflecting
       this.__reflectingProperty = propName;
       // eslint-disable-next-line @typescript-eslint/no-explicit-any
-      this[propName as keyof this] = fromAttribute!(value, options.type) as any;
+      this[propName as keyof this] = converter.fromAttribute!(
+        value,
+        options.type
+      ) as any;
```
Comment (augustjk) [inline packages/reactive-element/src/reactive-element.ts:1134]: The eslint comment should be moved to be above this line

**Comment by justinfagnani** [comment]
Thanks for the additional review @augustjk 

@nebarf with those comments addressed this looks great!

**Review by augustjk — APPROVED** [review]
Awesome, thank you! I just went ahead and combined the changeset files together which is our preferred way.

**Review by justinfagnani — APPROVED** [review]
LGTM!
