### PR TITLE
Some small, subtle fixes to 3.0 decorators

### LINKED ISSUE #4222: Fix issues with decorators discovered syncing into google3

### PR DESCRIPTION
**Pull request by rictic**
Based on fixing internal tests that failed.

Fixes #4222

### CODE REVIEW

File: packages/reactive-element/src/decorators/property.ts [hunk 1]
```diff
@@ -79,6 +79,8 @@ const legacyProperty = (
   // define in createProperty() with the original descriptor. We don't do this
   // for fields, which don't have a descriptor, because this could overwrite
   // descriptor defined by other decorators.
+  // for fields, which don't have a descriptor, because this could overwrite
+  // descriptor defined by other decorators.
```
Comment (augustjk) [inline packages/reactive-element/src/decorators/property.ts:83]: these lines got duplicated somehow

Comment (rictic) [reply packages/reactive-element/src/decorators/property.ts]: So they did! Fixed

File: packages/reactive-element/src/decorators/state.ts [hunk 2]
```diff
@@ -41,6 +41,7 @@ export type InternalPropertyDeclaration<Type = unknown> =
 export function state(options?: StateDeclaration) {
   return property({
     ...options,
+    state: true,
```
Comment (augustjk) [inline packages/reactive-element/src/decorators/state.ts:44]: Just for my own curiosity, does this actually have an effect beyond forcing `attribute: false` that's below this line?

File: packages/reactive-element/src/decorators/query-all.ts [hunk 3]
```diff
@@ -59,13 +59,25 @@ let fragment: DocumentFragment;
...
       get(this: ReactiveElement) {
         const container =
           this.renderRoot ?? (fragment ??= document.createDocumentFragment());
         return container.querySelectorAll(selector);
       },
     };
+    if (typeof name !== 'object' && extendedReflect.decorate) {
+      // If we're called as a legacy decorator, and Reflect.decorate is present
+      // then we have no guarantees that the returned descriptor will be
+      // defined on the class, so we must apply it directly ourselves.
```
Comment (augustjk) [inline packages/reactive-element/src/decorators/query-all.ts:77]: I don't fully understand why this is the case (I have a vague memory of you talking about it), but I do appreciate the comment stating this behavior.

**Review by augustjk — APPROVED** [review]
Nice! I'm less familiar with the new decorator code but the changes here mostly makes sense to me.

File: packages/reactive-element/src/decorators/state.ts (hunk 2 above)
Comment (rictic) [reply packages/reactive-element/src/decorators/state.ts:44]: Only for code that actually introspects on the property options, which it turns out some does!

File: packages/reactive-element/src/decorators/query-all.ts (hunk 3 above)
Comment (rictic) [reply packages/reactive-element/src/decorators/query-all.ts:77]: TypeScript experimental decorators defer to the nonstandard Reflect.decorate if it's present, and some (all?) Angular apps install a very ancient version that ignores the returned value

File: packages/reactive-element/src/decorators/state.ts (hunk 2 above)
Comment (AndrewJakubowicz) [reply packages/reactive-element/src/decorators/state.ts:44]: Worth adding an inline comment on why both are needed?

File: packages/reactive-element/src/decorators/query.ts [hunk 4]
```diff
@@ -112,11 +114,24 @@ export function query(selector: string, cache?: boolean): QueryDecorator {
...
       // experimental decorators.
-      return {
+      resultDescriptor = {
+        ...descriptorDefaults,
         get(this: ReactiveElement) {
           return doQuery(this);
         },
       };
     }
+    if (typeof nameOrContext !== 'object' && extendedReflect.decorate) {
```
Comment (AndrewJakubowicz) [inline packages/reactive-element/src/decorators/query.ts:124]: Could a unit test be added? Although I assume this is tested internally via TAP so can punt.

File: packages/reactive-element/src/decorators/query-assigned-elements.ts [hunk 5]
```diff
@@ -93,5 +97,13 @@ export function queryAssignedElements(
         ) as V;
       },
     };
+    if (typeof name !== 'object' && extendedReflect.decorate) {
+      // If we're called as a legacy decorator, and Reflect.decorate is present
+      // then we have no guarantees that the returned descriptor will be
+      // defined on the class, so we must apply it directly ourselves.
+      Object.defineProperty(obj, name, descriptor);
+      return;
+    }
```
Comment (AndrewJakubowicz) [inline packages/reactive-element/src/decorators/query-assigned-elements.ts:106]: Is code size smaller to have this imported once for each decorator from `base.js`? Can ignore.

**Review by AndrewJakubowicz — APPROVED** [review]
Very subtle issue. Exceptional find and fix!

File: packages/reactive-element/src/decorators/base.ts [hunk 6]
```diff
@@ -17,3 +17,10 @@ export type Constructor<T> = {
   // eslint-disable-next-line @typescript-eslint/no-explicit-any
   new (...args: any[]): T;
 };
+
+export const descriptorDefaults = {
+  enumerable: true,
+  configurable: true,
+} as const;
+
+export const extendedReflect: typeof Reflect & {decorate?: unknown} = Reflect;
```
Comment (justinfagnani) [inline packages/reactive-element/src/decorators/base.ts:26]: Add comment - why can't you use Reflect directly?

File: packages/reactive-element/src/decorators/query-all.ts [hunk 7]
```diff
@@ -59,13 +59,25 @@ let fragment: DocumentFragment;
  * @category Decorator
  */
 export function queryAll(selector: string): QueryAllDecorator {
-  return (() => {
-    return {
+  return ((
+    obj: object,
+    name: PropertyKey | ClassAccessorDecoratorContext<unknown, unknown>
```
Comment (justinfagnani) [inline packages/reactive-element/src/decorators/query-all.ts:64]: I think this:

```suggestion
    nameOrContext: PropertyKey | ClassAccessorDecoratorContext<unknown, unknown>
```

will make the `typeof name !== 'object'` below a lot more clear.

File: packages/reactive-element/src/decorators/base.ts (hunk 6 above)
Comment (justinfagnani) [inline packages/reactive-element/src/decorators/base.ts:26]: I only see this accessed as `extendedReflect.decorate` coerced to a boolean, so could you just export that boolean?

```suggestion
export const reflectDecorateExists = 'decorate' in Reflect;
```

File: packages/reactive-element/src/decorators/base.ts [hunk 8]
```diff
@@ -17,3 +17,10 @@ export type Constructor<T> = {
   // eslint-disable-next-line @typescript-eslint/no-explicit-any
   new (...args: any[]): T;
 };
+
+export const descriptorDefaults = {
```
Comment (justinfagnani) [inline packages/reactive-element/src/decorators/base.ts:21]: I don't really want to commit to these exports being in the public API. Can you mark `@internal`? And can these be renamed by Terser?

File: packages/reactive-element/src/decorators/query-assigned-elements.ts [hunk 9]
```diff
@@ -93,5 +97,13 @@ export function queryAssignedElements(
         ) as V;
       },
     };
+    if (typeof name !== 'object' && extendedReflect.decorate) {
+      // If we're called as a legacy decorator, and Reflect.decorate is present
+      // then we have no guarantees that the returned descriptor will be
+      // defined on the class, so we must apply it directly ourselves.
+      Object.defineProperty(obj, name, descriptor);
+      return;
```
Comment (justinfagnani) [inline packages/reactive-element/src/decorators/query-assigned-elements.ts:105]: is it bad to let this fall through and return the descriptor?

File: packages/reactive-element/src/decorators/query-assigned-elements.ts [hunk 10]
```diff
@@ -93,5 +97,13 @@ export function queryAssignedElements(
         ) as V;
       },
     };
+    if (typeof name !== 'object' && extendedReflect.decorate) {
```
Comment (justinfagnani) [inline packages/reactive-element/src/decorators/query-assigned-elements.ts:100]: I think you could even wrap this into a function exported from base, like:

base.ts:
```ts
/**
  * Ensures that the property is defined even if we're called as a legacy decorator, and
  *  Reflect.decorate is present. In that case we have no guarantees that a descriptor 
  * returned from a decorator will be
  * defined on the class, so we must apply it directly ourselves.
  * Also applies defaults...
  */
export const ensureProperty = (obj, nameOrContext, descriptor) => {
  descriptor = {
      enumerable: true,
      configurable: true,
      ...descriptor,
  };
  if (typeof name !== 'object' && extendedReflect.decorate) {
      Object.defineProperty(obj, name, descriptor);
      return;
  }
  return descriptor;
}
```

Here:
```ts
return ensureProperty(obj, name, descriptor);
```

File: packages/reactive-element/src/decorators/base.ts (hunk 8 above)
Comment (rictic) [reply packages/reactive-element/src/decorators/base.ts]: Marked as @internal

Looks like it's not renamed, Terser emits:

```js
const e=(e,t,c)=>(c.configurable=!0,c.enumerable=!0,Reflect.decorate&&"object"!=typeof t&&Object.defineProperty(e,t,c),c);export{e as desc};
```

Gave it a short name since it's not minified, and marked it as internal

File: packages/reactive-element/src/decorators/query-assigned-elements.ts (hunk 10 above)
Comment (rictic) [reply packages/reactive-element/src/decorators/query-assigned-elements.ts]: Done. Gave it a short name for size and because it has no easily explicable name, and just mutated the descriptor rather than allocating a new one, since we know all the cases where this is called and they're all ok with mutation

File: packages/reactive-element/src/decorators/query-assigned-elements.ts (hunk 9 above)
Comment (rictic) [reply packages/reactive-element/src/decorators/query-assigned-elements.ts]: Let's try it, might have to revert it internally, but we'll see

File: packages/reactive-element/src/decorators/query-all.ts (hunk 7 above)
Comment (rictic) [reply packages/reactive-element/src/decorators/query-all.ts:64]: Less necessary now that we're just passing this along

File: packages/reactive-element/src/decorators/base.ts (hunk 6 above)
Comment (rictic) [reply packages/reactive-element/src/decorators/base.ts]: Done
