### PR TITLE
[labs/task] Allow tasks to have an initial value

### LINKED ISSUE #2367: [labs/task] Allow setting initial data
# Description

If you do navigation preloading or similar you may already have the data for the task at component creation time. Then it would make sense to be able to either set that data manually at Task creation time or using some attributes.

The simplest but probably also most unclean change would be to make `_value`

https://github.com/lit/lit/blob/57a53e1c85216a4255e9f700402ef6cbe37a4167/packages/labs/task/src/task.ts#L108

 public and name it `value`

# Steps to Reproduce

```ts
import {Task} from '@lit-labs/task';

this._apiTask = new Task(
  this,
  taskFunction,
  () => /** @type {[URLSearchParams]} */ ([this.history.url.searchParams])
);
 if (this.initial !== undefined) {
  this._apiTask.status = TaskStatus.COMPLETE;
  // TODO FIXME don't use this private attribute that got minified
  this._apiTask.P = this.initial;
}
```

### PR DESCRIPTION
**Pull request by justinfagnani**
Fixes #2367 
Supersedes #2836 

This adds an `initialValue` config option. If set, the task is put into the COMPLETE status and `initialValue` is assigned to the current value of the task. Initial args are read off synchronously so that the task won't auto-run until the args change.

This is useful for when an element has the initial data available synchronously (maybe from hydration?) and wants to make the task look like it has completed a first run.

### CODE REVIEW

File: packages/labs/task/src/task.ts [hunk 1]
```diff
@@ -185,6 +195,13 @@ export class Task<
     if (taskConfig.autoRun !== undefined) {
       this.autoRun = taskConfig.autoRun;
     }
+    // Providing initialValue puts the task in COMPLETE state and stores the
+    // args immediately so it only runs when they change again.
+    if ('initialValue' in taskConfig) {
+      this._value = taskConfig.initialValue;
+      this.status = TaskStatus.COMPLETE;
+      this._previousArgs = this._getArgs?.();
+    }
```
Comment (rictic) [inline packages/labs/task/src/task.ts:204]: Beautiful!

File: packages/labs/task/src/test/task_test.ts [hunk 2]
```diff
@@ -225,6 +225,36 @@ suite('Task', () => {
...
+    initializing = false;
+    await renderElement(el);
+    assert.equal(el.task.status, TaskStatus.COMPLETE);
+    assert.equal(el.task.value, 'initial');
+    assert.equal(el.taskValue, 'initial');
+
+    // The task is complete, so waiting for it shouldn't change anything
+    await tasksUpdateComplete();
+    assert.equal(el.task.status, TaskStatus.COMPLETE);
+    assert.equal(el.task.value, 'initial');
```
Comment (rictic) [inline packages/labs/task/src/test/task_test.ts:246]: Consider asserting that assigning `el.a = 'a';` won't run the task

**Review by rictic — APPROVED** [review]

File: packages/labs/task/src/task.ts (hunk 1 above)
Comment (justinfagnani) [reply packages/labs/task/src/task.ts:204]: thanks!
