### PR TITLE
[labs/virtualizer] Fix #3481 and #3518

### LINKED ISSUE #3481: [labs/virtualizer] Error when immediately re-rendering (before async connect code runs)
### Which package(s) are affected?

Virtualizer (@lit-labs/virtualizer)

### Description

When using the latest `0.0.0-masonry-preview-20221107225026` preview, the virtualizer throws an error on initial render. It still seems to work after that.

The error:
```
Virtualizer.js:168 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'detach')
    at Virtualizer.disconnected (Virtualizer.js:168:1)
    at VirtualizeDirective._makeVirtualizer (virtualize.js:74:1)
    at VirtualizeDirective._updateVirtualizerConfig (virtualize.js:59:1)
    at VirtualizeDirective.update (virtualize.js:48:1)
    at VirtualizeDirective._$resolve (directive.ts:134:1)
    at resolveDirective (lit-html.ts:1075:1)
    at ChildPart._$setValue (lit-html.ts:1353:1)
    at TemplateInstance._update (lit-html.ts:1181:1)
    at ChildPart._commitTemplateResult (lit-html.ts:1525:1)
    at ChildPart._$setValue (lit-html.ts:1375:1)
```

This is with the following markup:

```
        <tbody @visibilityChanged=${this.#onVisibilityChanged}>
          ${virtualize({ items: this.items, renderItem: item => this.renderItem(item) })}
        </tbody>
```

This does not throw any error with `0.7.2`

### Reproduction

-

### Workaround

-

### Is this a regression?

Yes. This used to work, but now it doesn't.

### Affected versions

Failing in 0.0.0-masonry-preview-20221107225026, used to work in 0.7.2

### Browser/OS/Node environment

-

### PR DESCRIPTION
**Pull request by graynorton**
Fix #3481 and #3518

### CODE REVIEW

File: packages/labs/virtualizer/src/Virtualizer.ts [hunk 1]
```diff
@@ -764,42 +776,44 @@ export class Virtualizer {
...
+
   private _scheduleLayoutComplete() {
-    if (this._pendingLayoutComplete !== null) {
-      cancelAnimationFrame(this._pendingLayoutComplete);
+    // Don't do anything unless we have a pending promise
+    // And only request a frame if we haven't already done so
+    if (this._layoutCompletePromise && this._pendingLayoutComplete === null) {
+      // Wait one additional frame to be sure the layout is stable
+      this._pendingLayoutComplete = requestAnimationFrame(() =>
+        requestAnimationFrame(() => this._resolveLayoutCompletePromise())
```
Comment (usergenic) [inline packages/labs/virtualizer/src/Virtualizer.ts:803]: Interesting! I like the locality/cleanliness of expressing the extra nesting RAF here.  It appears to mean that resolving the layout complete promise is no longer deferrable past the second RAF, however, since `this._resolveLayoutCompletePromise()`.  I am trying to contrive a scenario where that would pose a risk...

Considering a case where _childrenSizeChanged() is called due to observation and that triggers a subsequent scheduleLayoutComplete but the subsequent one doesn't wait yet-another two animation frames--  I'll tell you what I'll make an issue to add more cases to the layout complete tests to verify expectations around cascading resize effects and the layoutComplete promise as a separate issue and approve this as is.

**Review by usergenic — APPROVED** [review]
LGTM

File: packages/labs/virtualizer/src/Virtualizer.ts (hunk 1 above)
Comment (graynorton) [reply packages/labs/virtualizer/src/Virtualizer.ts:803]: Yeah, a full set of `layoutComplete` tests would be great. I *think* any given cycle of child measurements and re-layouts is going to occur within a single frame, so believe this logic is ok—but we should certainly confirm via tests.
