### PR TITLE
fix(labs/gen-wrapper-*): fix module path error when generating wrapper code in windows

### LINKED ISSUE #4051: [labs/gen-wrapper-*] In Windows systems, the module path generated by the template wrapper is incorrect
### Which package(s) are affected?

React (@lit-labs/react)

### Description

In Windows systems, the module path generated by the template wrapper is incorrect.

In [labs/analyzer/src/lib/analyzer.ts](https://github.com/lit/lit/blob/main/packages/labs/analyzer/src/lib/analyzer.ts#L73-L82), we use `path.normalize` to adapt file paths to various operating systems:

image

This value will be passed down and eventually used in [packages/labs/gen-wrapper-vue/src/lib/wrapper-module-template-sfc.ts](https://github.com/lit/lit/blob/main/packages/labs/gen-wrapper-vue/src/lib/wrapper-module-template-sfc.ts#L24-L34)

image

It will cause the generated wrapper code to be incorrect in the Windows system:
image

### Reproduction

execute `lit labs gen --framework=vue` in windows system.

### Workaround

We should replace `\` with `/` of module path when generating the wrapper code. I will solve this problem in #4052

### Is this a regression?

Yes. This used to work, but now it doesn't.

### Affected versions

The lasted version

### Browser/OS/Node environment

Node version: 18.12.0

### PR DESCRIPTION
**Pull request by zh-lx**
Fix module path error when generating wrapper code in windows. close #4051

### CODE REVIEW

**Comment by augustjk** [comment]
Thanks for the PR! If possible we'd like to see a test for this fix so we'll be able to catch this.

File: packages/labs/gen-wrapper-vue/src/lib/rename-template.ts [hunk 1]
```diff
@@ -19,16 +21,28 @@ const __filename = fileURLToPath(import.meta.url);
...
+          filePath,
+          \`\${filePath.replace('.vue.d.ts', '.d.ts')}\`,
+          (err) => {
+            console.log(err);
+          }
+        );
       }
-    )
+    } else if (stat.isDirectory()) {
+      traverseRename(filePath); // 递归遍历子目录
```
Comment (augustjk) [inline packages/labs/gen-wrapper-vue/src/lib/rename-template.ts:42]: Could you update the comment to be in English? It should update in the golden too.

File: packages/labs/gen-wrapper-vue/src/lib/vite.config-template.ts [hunk 2]
```diff
@@ -35,14 +36,22 @@ export default {
...
-        entryFileNames: ({ name }) => \`\${name}.js\`,
+        // For subpath component, we should output it in subpath.
+        // Otherwise, if there are files with the same file name in the subPath and rootPath,
+        // output to the same directory will conflict.
+        entryFileNames: ({ name, facadeModuleId }) => {
+          const sourceFileDir = path.dirname(facadeModuleId);
+          const relativePath = path.relative(__dirname, sourceFileDir);
+          const targetName = path.join(relativePath, \`\${name}.js\`).replace(/\\\\/g, '/').replace(/^src\\\//, '');
+          return targetName;
+        },
```
Comment (augustjk) [inline packages/labs/gen-wrapper-vue/src/lib/vite.config-template.ts:54]: I'm trying to think over this logic. I think we might be able to do `preserveModules: true` and `preserveModulesRoot: 'src'` to avoid this. https://rollupjs.org/configuration-options/#output-preservemodulesroot

**Review by augustjk — CHANGES_REQUESTED** [review]
Thanks for adding the sub element to test!
I have a couple requests for changes, but I think overall this is looking good.

We also need a changeset entry as per https://github.com/lit/lit/pull/4052#issuecomment-1653957375 but I'd be happy to do that before merging if you're unsure.

File: packages/labs/gen-wrapper-vue/src/lib/rename-template.ts (hunk 1 above)
Comment (zh-lx) [reply packages/labs/gen-wrapper-vue/src/lib/rename-template.ts]: Ok, I have changed it to English.

File: packages/labs/gen-wrapper-vue/src/lib/vite.config-template.ts (hunk 2 above)
Comment (zh-lx) [reply packages/labs/gen-wrapper-vue/src/lib/vite.config-template.ts]: I have used `preserveModules` to replace these code and it does work.

File: packages/labs/gen-wrapper-vue/goldens/test-element-a/scripts/rename.js [hunk 3]
```diff
@@ -10,15 +10,27 @@ const __filename = fileURLToPath(import.meta.url);
...
+          filePath,
+          `${filePath.replace('.vue.d.ts', '.d.ts')}`,
+          (err) => {
+            console.log(err);
+          }
+        );
       }
-    );
+    } else if (stat.isDirectory()) {
+      traverseRename(filePath); // transfer the sub directory and rename file
```
Comment (AndrewJakubowicz) [inline packages/labs/gen-wrapper-vue/goldens/test-element-a/scripts/rename.js:31]: Nit: Change `transfer` to `traverse`

Comment (AndrewJakubowicz) [reply packages/labs/gen-wrapper-vue/goldens/test-element-a/scripts/rename.js:31]: Whoops - this is the golden file. Disregard.

File: packages/labs/gen-wrapper-vue/src/lib/rename-template.ts [hunk 4]
```diff
@@ -19,16 +21,28 @@ const __filename = fileURLToPath(import.meta.url);
...
+          filePath,
+          \`\${filePath.replace('.vue.d.ts', '.d.ts')}\`,
+          (err) => {
+            console.log(err);
+          }
+        );
       }
-    )
+    } else if (stat.isDirectory()) {
+      traverseRename(filePath); // transfer the sub directory and rename file
```
Comment (AndrewJakubowicz) [inline packages/labs/gen-wrapper-vue/src/lib/rename-template.ts:42]: Rename `transfer` to `traverse`, and change `file` to `files`.

**Review by AndrewJakubowicz — COMMENTED** [review]
I took a quick look and this is looking very good. The tests are excellent.

**Comment by zh-lx** [comment]
> 
I'm not sure how to write the changeset, but I would appreciate it if you could to that.

**Review by augustjk — APPROVED** [review]
Thank you very much! This is great! I added a changeset file and tweaked the comment wording a bit.
