### PR TITLE
Make taskComplete a getter so that errors are only thrown when requested

### LINKED ISSUE #3946: Issue with uncaught exceptions thrown when a task function rejects/throws an error
### Which package(s) are affected?

Task (@lit-labs/task)

### Description

See this discord thread for a full description:
https://discord.com/channels/1012791295170859069/1047015641225371718/threads/1075045145596137582
@justinfagnani mentioned towards the bottom that an issue was going to be raised but I couldn't find anything so am raising it now as I have just run into this problem and currently the only solution is a little ugly namely manually adding a do nothing catch to 'taskComplete' to stop the error propogating.

### Reproduction

See https://discord.com/channels/1012791295170859069/1047015641225371718/threads/1075045145596137582

### Workaround

See https://discord.com/channels/1012791295170859069/1047015641225371718/threads/1075045145596137582

### Is this a regression?

No or unsure. This never worked, or I haven't tried before.

### Affected versions

2.1.1

### Browser/OS/Node environment

N/A

### PR DESCRIPTION
**Pull request by e111077**
fixes #3946

Task now will not throw errors unless `taskComplete` is specifically called. In that case the user should catch the error on `taskComplete`.

**GOTCHAS:**

The following case is a gotcha but it's just how promises work:

```ts
taskThatThrowsAnError.taskComplete.catch(() => {});

// this will throw an error. User needs to catch here too or await previous line
await taskThatThrowsAnError.taskComplete;
```

see reproduction of native behavior [here](https://lit.dev/playground/#gist=3c498dfa3f2dc6f066527b561a015a32)

### CODE REVIEW

File: packages/labs/task/src/task.ts [hunk 1]
```diff
@@ -44,6 +44,7 @@ export interface TaskConfig<T extends ReadonlyArray<unknown>, R> {
   task: TaskFunction<T, R>;
   args?: ArgsFunction<T>;
   autoRun?: boolean;
+  throwErrors?: boolean;
```
Comment (justinfagnani) [inline packages/labs/task/src/task.ts:47]: I would love to find a way to address this without a new config option. I think an expansion of options can be bad DX as users have to decide whether they should say the option or not, and what the default it.

I was thinking we could make taskComplete a getter, so we don't even create a promise that could have an uncaught error. The getter would have to create an already resolved promise if the task is complete.

Your comment about an error renderer is insightful! It's be great if we detected an error renderer and also suppressed uncaught errors. And maybe the same for the onError callback?

Comment (e111077) [reply packages/labs/task/src/task.ts:47]: What is the advantage of the getter? Is it just not having to create the promise in the first place? If so, I feel like the bloat of the extra checks around it might outweigh the memory savings if that's the only reason

Comment (e111077) [reply packages/labs/task/src/task.ts:47]: I like the onError and render.errror suggestion. Would remove the need for the config option

Comment (justinfagnani) [reply packages/labs/task/src/task.ts:47]: The getter is so that we avoid even making the promise until it's been asked for, so by default we don't get any uncaught errors. Then if a user does access the promise, and don't handle the error, they'll get the warning if they don't have the error, but in that case they really should get the warning.

Comment (justinfagnani) [reply packages/labs/task/src/task.ts:47]: Actually, I think with the on-demand promise creation, you won't need to look at error handlers, since the warning would only ever be made of the user gets a promise and doesn't handle it correctly.

Comment (e111077) [reply packages/labs/task/src/task.ts:47]: issues with the automatic error handling via `shouldCatch = !!this.onError || this.render.error` – it's difficult to determine whether the user has an error handler in the error message. We could do something like:

`this._hasErrorRenderer = this._hasErrorRenderer || !!renderer.error` in `render()`, but that requires:

1. The user to have called `render()` at least once with an `error` option before the task has completed
   - The user could be rendering their error renderer _after_ the task has completed in a conditional template
2. The user to continue rendering the `error` renderer because the logic is optimistic that there is an error handler to handle the following case:
   - ```js
      ${task.render({error: ... })}
      ${task.render({complete: ... })}
      ```

I'd also wager that the user having to handle catch on `taskComplete` is not great because it doesn't make sense that you'd have to catch on `taskComplete` as opposed to the task itself handling it.

WDYT of:

- Do not turn `taskComplete` into a getter
- No `throwErrors` and just catch every time and it's up to the user to use our intended API to handle errors at all time

Comment (justinfagnani) [reply packages/labs/task/src/task.ts:47]: I think making `taskComplete` a getter solves this. There's no need to look for an error handler in render. The logic should be simple: if a user called `.taskCompete`, reject that promise on error, if not, there's no promise to reject and no unhandled rejection.

We already do reject the taskComplete promise, so this wouldn't even be a breaking change. If we don't reject we have to at least resolve it, so we don't leave it hanging, but I think that's a bit weird.

Comment (e111077) [reply packages/labs/task/src/task.ts]: took a while to untangle the logic in my head, but tests should be robust. PTAL

Comment (e111077) [reply packages/labs/task/src/task.ts]: updated main comment with a gotcha, but it's just how Promises work

File: packages/labs/task/src/task.ts [hunk 2]
```diff
@@ -226,17 +246,19 @@ export class Task<
...
           } catch {
             // Ignore user errors from onError.
           }
           this.status = TaskStatus.ERROR;
-          this._rejectTaskComplete(error);
+          this._rejectTaskComplete?.(error);
         }
         this._value = result as R;
+        // The run's ended so don't generate a task complete promise and either
+        // return the existing, resolved promise or a new resolved promise.
```
Comment (justinfagnani) [inline packages/labs/task/src/task.ts:261]: Is this comment still valid?

I think this is the spot where you can do:

```ts
this._resolveTaskComplete = undefined;
this._rejectTaskComplete = undefined;
this._taskComplete = undefined;
```

**Comment by justinfagnani** [comment]
Nice!

I think the method you have here is fine to go in, but I added a suggestion that might make things simper.

File: packages/labs/task/src/task.ts (hunk 2 above)
Comment (e111077) [reply packages/labs/task/src/task.ts:261]: oops not valid anymore. No longer necessary since I do that inthe taskComplete getter.

File: packages/labs/task/src/task.ts [hunk 3]
```diff
@@ -115,21 +115,53 @@ export class Task<
...
   /**
    * A Promise that resolve when the current task run is complete.
    *
    * If a new task run is started while a previous run is pending, the Promise
    * is kept and only resolved when the new run is completed.
    */
-  taskComplete!: Promise<R>;
+  get taskComplete(): Promise<R> {
+    // True only when called for the first time or after a run is complete.
+    const lastPromiseCompletedOrFirstRequest = !this._resolveTaskComplete;
```
Comment (justinfagnani) [inline packages/labs/task/src/task.ts:131]: I think this could be a _little_ simpler if you clear the promise state in `run()` so that if `this._taskComplete` is defined here you just always return it. Then if it's not defined you have the branches to create it with either a pending promise or a resolved one based on the status.

Comment (e111077) [reply packages/labs/task/src/task.ts]: you are right, MUCH cleaner! thanks!

**Comment by e111077** [comment]
oh no tests are failing on sauce but not locally!

File: packages/labs/task/src/task.ts [hunk 4]
```diff
@@ -115,21 +115,47 @@ export class Task<
...
+      this._taskComplete = new Promise((res, rej) => {
+        this._resolveTaskComplete = res;
+        this._rejectTaskComplete = rej;
+      });
+
+      // Otherwise we are at a run's completion or this is the first request
+      // and we are not in the middle of a task (i.e. INITIAL).
+    } else {
+      this._resolveTaskComplete = undefined;
+      this._rejectTaskComplete = undefined;
```
Comment (justinfagnani) [inline packages/labs/task/src/task.ts:149]: These should always already be undefined

File: packages/labs/task/src/task.ts [hunk 5]
```diff
@@ -115,21 +115,47 @@ export class Task<
...
    *
    * If a new task run is started while a previous run is pending, the Promise
    * is kept and only resolved when the new run is completed.
    */
-  taskComplete!: Promise<R>;
+  get taskComplete(): Promise<R> {
+    // If a task exists, return the cached promise. This is true in the case
+    // where the user has called taskComplete in pending or completed state
+    // before and has not run a new task since.
+    if (this._taskComplete) {
```
Comment (justinfagnani) [inline packages/labs/task/src/task.ts:133]: Optional, some 🏌️ :

```ts
return this._taskComplete ??= this.status === TaskStatus.PENDING
  ? new Promise((res, rej) => {
      this._resolveTaskComplete = res;
      this._rejectTaskComplete = rej;
    })
  : Promise.resolve(this._value!);
```

(except with your nice comments added back in)

File: packages/labs/task/src/task.ts [hunk 6]
```diff
@@ -191,15 +213,20 @@ export class Task<
...
     args ??= this._getArgs?.();
+
+    // Clear the last complete task in initial because it may be a resolved
+    // promise. Also clear if complete or error because the value returned by
+    // awaiting taskComplete may have changed since last run.
     if (
       this.status === TaskStatus.COMPLETE ||
-      this.status === TaskStatus.ERROR
+      this.status === TaskStatus.ERROR ||
+      this.status === TaskStatus.INITIAL
```
Comment (justinfagnani) [inline packages/labs/task/src/task.ts:223]: This is the same as `this.status !== TaskStatus.PENDING` now, yeah?

Which brings up an interesting question: is `run()` doing the correct thing when called on an already pending task? No need to address that in the PR, but maybe we're missing a test?

**Review by justinfagnani — APPROVED** [review]
Awesome!!

File: packages/labs/task/src/task.ts (hunk 5 above)
Comment (e111077) [reply packages/labs/task/src/task.ts:133]: oh yikes, veto!

Comment (e111077) [reply packages/labs/task/src/task.ts:133]: Resolving with ACK as I think clarity is more important than the unbundled byte size here

Comment (justinfagnani) [reply packages/labs/task/src/task.ts:133]: fwiw, I like the readability with the logical and assignment and ternary. The logical and assignment tells me that this is using the current value if available, or computing a new one. The ternary tells me that we're computing a single value based on a condition. To me that's more apparent than with the if/else block with multiple assignment statements form, since any other logic could be in the if/else blocks.

It also compresses better even after minification because there's only one reference to `this._taskComplete` instead of five. `this.` is something a minifier can't get rid of even if it changes the property name.

File: packages/labs/task/src/task.ts [hunk 7]
```diff
@@ -115,21 +115,45 @@ export class Task<
...
+    // cleared by .run().
+    if (this.status === TaskStatus.PENDING) {
+      this._taskComplete = new Promise((res, rej) => {
+        this._resolveTaskComplete = res;
+        this._rejectTaskComplete = rej;
+      });
+
+      // Otherwise we are at a task run's completion or this is the first
+      // request and we are not in the middle of a task (i.e. INITIAL).
+    } else {
```
Comment (rictic) [inline packages/labs/task/src/task.ts:147]: What about if taskStatus is ERROR?
