### PR TITLE
[labs/react] Fix type compatibility with Preact when adding children

### LINKED ISSUE #4138: [labs/react] Typescript errors with react wrapped component in Vite Preact Typescript template
### Which package(s) are affected?

React (@lit-labs/react)

### Description

Trying out shoelace in a fresh vite preact-ts template and getting a couple of typescript issues.

(shoelace 2.8.0 which is using @lit-labs/react 2.0.1, NOTE: react wrapper files are generated on build [here](https://github.com/shoelace-style/shoelace/blob/next/scripts/make-react.js#L58-L68))

With the following code I am getting 2 different typescript errors:

```tsx
import { useState } from 'preact/hooks';
import SlButton from '@shoelace-style/shoelace/dist/react/button/index.js';
import SlIcon from '@shoelace-style/shoelace/dist/react/icon/index.js';

export default function Test() {
    const [count, setCount] = useState(0);
    return (
        <SlButton onClick={() => setCount((count) => count + 1)} variant="primary">
            <SlIcon slot="prefix" library="system" name="star-fill" />
            count is {count}
        </SlButton>
    );
}
```

SlButton type error (not an error in stackblitz example but it is locally in vscode):
```
'SlButton' cannot be used as a JSX component.
  Its type 'ReactWebComponent<SlButton, { onSlBlur: EventName<SlBlurEvent>; onSlFocus: EventName<SlFocusEvent>; onSlInvalid: EventName<SlInvalidEvent>; }>' is not a valid JSX element type.
    Type 'ForwardRefExoticComponent<Omit<HTMLAttributes<SlButton>, "onSlBlur" | "onSlFocus" | "onSlInvalid"> & Partial<Omit<SlButton, keyof HTMLElement>> & EventListeners<...> & RefAttributes<...>>' is not assignable to type 'FunctionComponent<any>'.
      Type 'ReactNode' is not assignable to type 'VNode<any> | null'.
        Type 'undefined' is not assignable to type 'VNode<any> | null'.ts(2786)
```

SlIcon has this error:
```
Type 'Element' is not assignable to type 'ReactNode'.
  Property 'children' is missing in type 'VNode<any>' but required in type 'ReactPortal'.ts(2322)
```

If I change SlIcon to a div:
```tsx
<div slot="prefix"></div>
```

The typescript error is just:
```
Type 'Element' is not assignable to type 'ReactNode'.ts(2322)
```

### Reproduction

Here is a stackblitz example (note: the first error does not appear here for me, only in local vscode):
https://stackblitz.com/edit/vitejs-vite-k7w2nf?file=src%2Fapp.tsx&terminal=dev

### Workaround

I have not found a workaround

### Is this a regression?

No or unsure. This never worked, or I haven't tried before.

### Affected versions

2.0.1

### Browser/OS/Node environment

Browser: Edge 116.0.1938.54
OS: Windows 11 22621.2215
Node version: 18.11.0
Npm version: 9.2.0

### PR DESCRIPTION
**Pull request by augustjk**
Fixes #4138

Content placed in children position in JSX are typed differently depending on whether it's React or Preact project. Children typing in Preact projects were incompatible with `children` prop of our wrapped components as they only accepted `React.ReactNode` which was more restrictive than what Preact considers as valid renderable child.

This PR adds children typing that's compatible with both React and Preact.

~~Testing for this fix working in Preact was done manually in a working branch for https://github.com/lit/lit/pull/4111. I'd be okay with holding off on merging this until I can do the updates to that branch to demonstrate the fix.~~
Mentioned PR has been merged and this branch has been rebased to that.

### CODE REVIEW

File: packages/labs/react/src/create-component.ts [hunk 1]
```diff
@@ -48,15 +48,25 @@ export type ReactWebComponent<
...
+  | undefined;
+
+// Acceptable props to the React component.
 type ComponentProps<I, E extends EventNames = {}> = Omit<
   React.HTMLAttributes<I>,
-  keyof E
+  // Omit keyof E to prefer provided event handler mapping over React's
+  // built-in event handler props.
+  | keyof E
+  // Omit children to replace with out own that's compatible with Preact.
```
Comment (AndrewJakubowicz) [inline packages/labs/react/src/create-component.ts:66]: Typo: `with out own` -> `with our own`

File: packages/labs/react/src/create-component.ts [hunk 2]
```diff
@@ -48,15 +48,25 @@ export type ReactWebComponent<
 // lifecycle methods or allow user to explicitly provide props.
 type ElementProps<I> = Partial<Omit<I, keyof HTMLElement>>;
 
-// Acceptable props to the React component. Omit keyof E from HTMLAttributes to
-// prefer provided event handler mapping over React's built-in event handler
-// props.
+// Child type compatible with both React and Preact.
```
Comment (AndrewJakubowicz) [inline packages/labs/react/src/create-component.ts:51]: Is it worth adding some additional details/references for how/where this type was derived from?

**Review by AndrewJakubowicz — APPROVED** [review]
LGTM

It might be nice to land the Preact example, then land this with the children added to the example, but not too fussed with order.

Great stuff!

File: packages/labs/react/src/create-component.ts (hunk 1 above)
Comment (augustjk) [reply packages/labs/react/src/create-component.ts]: Thanks for catching, done!

File: packages/labs/react/src/create-component.ts (hunk 2 above)
Comment (augustjk) [reply packages/labs/react/src/create-component.ts]: Done.

**Comment by augustjk** [comment]
Rebased off of main with preact example merged, and addressed TODO that adds an element child to the wrapped component. Type test for it is passing. https://github.com/lit/lit/actions/runs/6005198623/job/16287421462?pr=4142#step:8:305
