### PR TITLE
[lit-html] Static `html` should not add consumed value to `TemplateResult`

### LINKED ISSUE #2246: [labs/ssr] Cannot SSR a dynamic tag with `unsafeStatic`
https://gist.github.com/shakyShane/423b19e9f479b06369eb90f4f503310a

The following stand-alone code examples both cause the error `Error: unexpected final partIndex: 0 !== 1`. 

I'm using `unsafeStatic` in a controlled way (eg: not user-provided data).

```js
import "@lit-labs/ssr/lib/render-with-global-dom-shim.js";
import { render as renderDomShim } from "@lit-labs/ssr/lib/render-with-global-dom-shim.js";
import { html, unsafeStatic } from 'lit/static-html.js'
import { LitElement } from 'lit'

/**
 * Rendering a static `<p>` fails
 *
 * ```
 * Error: unexpected final partIndex: 0 !== 1
 * ```
 */
const staticP = unsafeStatic('p');
for (const part of renderDomShim(html`<${staticP}>hello</${staticP}>`)) {
  console.log(part);
}

/**
 * Rendering a custom element also fails
 */
customElements.define('any-thing', class extends LitElement {
  render() {
    return html`<p>Hello world</p>`
  }
})

const element = unsafeStatic('any-thing');
for (const part of renderDomShim(html`<${element}>hello</${element}>`)) {
  console.log(part);
}
```

Any help will be greatly appreciated :)

### PR DESCRIPTION
**Pull request by augustjk**
Fixes #2246 

SSR of static html was erroring due to mismatch of `partIndex` as described in issue above because we were comparing that to the length of the `values` array in `TemplateResult`.

When a static value was the last value of a template, it ended up adding the static value object to the `TemplateResult`. This wasn't an issue if a non-static value was the last value.

i.e.
```js
const tag = literal`p`;
const template = html`<${tag}>Hello, ${this.name}!</${tag}`;
```
resulted in
```js
{
  strings: ['<p>Hello, ', '!</p>'],
  values: ['World', {_$litStatic$: 'p', r: Symbol()}],
}
```
when it should be
```js
{
  strings: ['<p>Hello, ', '!</p>'],
  values: ['World'],
}
```

In client rendering this wasn't an issue as we just never accessed that value. In SSR, it was causing the error due to the unexpected extra length.

### CODE REVIEW

File: packages/lit-html/src/static.ts [hunk 1]
```diff
@@ -131,7 +131,10 @@ export const withStatic =
         s += staticValue + strings[++i];
         hasStatics = true;
       }
-      dynamicValues.push(dynamicValue);
+      // If the last value is static, we don't need to push it.
+      if (i !== l) {
+        dynamicValues.push(dynamicValue);
```
Comment (justinfagnani) [inline packages/lit-html/src/static.ts:136]: Looking back at the original code, I don't love that `dynamicValue` apparently can hold a static value. Nice fix for now, but makes me want to clean this up later.

**Review by justinfagnani — APPROVED** [review]
Thanks for the quick turnaround!

**Comment by augustjk** [comment]
Failing tests here due to https://github.com/lit/lit/issues/3827
This PR https://github.com/lit/lit/pull/3828 is a band-aid for this issue if we want to unblock our tests for now.
