### PR TITLE
async-replace correctly re-renders when value is unchanged

### LINKED ISSUE #4408: [lit-html] Re-rendering an `asyncReplace` clears its value.
### Which package(s) are affected?

Lit Core (lit / lit-html / lit-element / reactive-element)

### Description

When a template using an `asyncReplace` is re-rendered without changing the iterable or its current value in the `asyncReplace`, the value is incorrectly cleared.

### Reproduction

https://lit.dev/playground/#gist=257917d929b16bd6f3109c81f121b992

Click the `requestUpdate` button

Expected:  the asyncReplace value should not change
Actual: the asyncReplace value is cleared (it is replaced if the iterable emits another value)

### Workaround

None.

### Is this a regression?

No or unsure. This never worked, or I haven't tried before.

### Affected versions

3.x

### Browser/OS/Node environment

All

### PR DESCRIPTION
**Pull request by sorvell**
Fixes #4408.

### CODE REVIEW

**Review by augustjk — APPROVED** [review]
Nice!

File: packages/lit-html/src/test/directives/async-replace_test.ts [hunk 1]
```diff
@@ -179,6 +179,30 @@ suite('asyncReplace', () => {
     assert.equal(stripExpressionMarkers(container.innerHTML), '<div>bar</div>');
   });
 
+  test('renders the same itetable value when re-rendered with no new value emitted', async () => {
```
Comment (AndrewJakubowicz) [inline packages/lit-html/src/test/directives/async-replace_test.ts:182]:
```suggestion
  test('renders the same iterable value when re-rendered with no new value emitted', async () => {
```
