### PR TITLE
[lit-html] Make RefOrCallback generic

### LINKED ISSUE #3966: [lit-html] RefOrCallback should be generic
### Which package(s) are affected?

Lit Core (lit / lit-html / lit-element / reactive-element)

### Description

`RefOrCallback` is not generic like `Ref<T>` and so does not forward a ref element type to `Ref`:

```ts
export type RefOrCallback = Ref | ((el: Element | undefined) => void);
```

This should be:

```ts
export type RefOrCallback<T = Element> = Ref<T> | ((el: T | undefined) => void);
```

### Reproduction

n/a

### Workaround

Make your own type.

### Is this a regression?

No or unsure. This never worked, or I haven't tried before.

### Affected versions

2.x

### Browser/OS/Node environment

all

### PR DESCRIPTION
**Pull request by justinfagnani**
Make `RefOrCallback` generic like `Ref<T>`.

Fixes #3966

### CODE REVIEW

File: packages/lit-html/src/directives/ref.ts [hunk 1]
```diff
@@ -38,7 +38,7 @@ const lastElementForContextAndCallback: WeakMap<
   WeakMap<Function, Element | undefined>
 > = new WeakMap();
 
-export type RefOrCallback = Ref | ((el: Element | undefined) => void);
+export type RefOrCallback<T = Element> = Ref<T> | ((el: T | undefined) => void);
```
Comment (rictic) [inline packages/lit-html/src/directives/ref.ts:41]: Should T extend Element?

**Review by rictic — APPROVED** [review]

File: packages/lit-html/src/directives/ref.ts (hunk 1 above)
Comment (justinfagnani) [reply packages/lit-html/src/directives/ref.ts:41]: Ref objects and callbacks could _technically_ be used with any type. `Ref` already doesn't have T extending Element, so this also seems inline with that.

File: .changeset/smooth-swans-sin.md [hunk 2]
```diff
@@ -0,0 +1,5 @@
+---
+'lit-html': patch
+---
```
Comment (augustjk) [inline .changeset/smooth-swans-sin.md:3]:
```suggestion
---
'lit-html': patch
'lit': patch
---
```

**Review by augustjk — APPROVED** [review]
