### PR TITLE
[labs/ssr] Make attribute handling case-insensitive

### LINKED ISSUE #3972: [labs/ssr] Uppercase in attribute name behaves differently
### Which package(s) are affected?

SSR (@lit-labs/ssr)

### Description

Reported in https://github.com/lit/lit/issues/3971#issuecomment-1601767854

In the `reactive-element` code for matching property to attribute, we lowercase the property name when we convert it to an attribute name, since that's what the DOM does. Looks like our DOM shim for SSR does not lowercase attribute names, and ends up with a mismatch.

### Reproduction

See linked issue comment above.

### Workaround

Supply all attributes as lowercase in template.

### Is this a regression?

No or unsure. This never worked, or I haven't tried before.

### Affected versions

latest

### Browser/OS/Node environment

.

### PR DESCRIPTION
**Pull request by augustjk**
Fixes #3972 

`ssr-dom-shim` was updated so all attribute methods lowercase the name as the browser does.

`LitElementRenderer` now also lowercases the attribute name when calling `attributeToProperty` with it.

### CODE REVIEW

**Comment by augustjk** [comment]
https://github.com/lit/lit/pull/3978 fixes the breaking test in the pipeline.

File: packages/labs/ssr/src/test/integration/tests/basic.ts [hunk 1]
```diff
@@ -4825,6 +4825,88 @@ export const tests: {[name: string]: SSRTest} = {
...
+          args: ['boundProp2'],
+          async check(assert: Chai.Assert, dom: HTMLElement) {
+            const el = dom.querySelector(
+              'le-mixed-attr-binding'
+            )! as LitElement;
+            await el.updateComplete;
+            assert.strictEqual((el as any).camelProp, 'boundProp2');
+          },
+          html: {
+            root: `<le-mixed-attr-binding camelProp="boundProp2" static></le-mixed-attr-binding>`,
```
Comment (AndrewJakubowicz) [inline packages/labs/ssr/src/test/integration/tests/basic.ts:4873]: Should `camelProp=` be `camelprop=`?

Comment (augustjk) [reply packages/labs/ssr/src/test/integration/tests/basic.ts]: Good eye! Turns out it doesn't matter because our DOM assertion treats those as equivalent, as the browser would lowercase it anyway. Still fixed it for consistency's sake.

**Comment by augustjk** [comment]
> #3978 fixes the breaking test in the pipeline.

Rebased to bring this in and local tests are now passing.

File: packages/labs/ssr/src/lib/lit-element-renderer.ts [hunk 2]
```diff
@@ -81,7 +81,7 @@ export class LitElementRenderer extends ElementRenderer {
     _old: string | null,
     value: string | null
   ) {
-    attributeToProperty(this.element as LitElement, name, value);
+    attributeToProperty(this.element as LitElement, name.toLowerCase(), value);
```
Comment (AndrewJakubowicz) [inline packages/labs/ssr/src/lib/lit-element-renderer.ts:84]: Everything in this change looks great! I'm only leaving a comment on this line because I don't have the full picture of what this change does.

My naive thoughts are that the logic for `attributeToProperty` results in calling `_$attributeToProperty` which may call a user defined `converter.fromAttribute`. Does making the name lower case here make sense in case a specific case sensitive name is expected down the line? Or will attributeToProperty always expect a lower case name because attributes from the DOM end up lower cased?

Thank you!

**Review by AndrewJakubowicz — APPROVED** [review]
Great!

File: packages/labs/ssr/src/lib/lit-element-renderer.ts (hunk 2 above)
Comment (augustjk) [reply packages/labs/ssr/src/lib/lit-element-renderer.ts:84]: I confirmed that the behavior in the client is that it always gets lowercase attributes, regardless of the casing of the attribute name in the original template. In this particular method, we're defining the `attributeChangedCallback` lifecycle and the browser turns all HTML attributes to lowercase so it would be consistent for us to do that in the server as well.

Comment (AndrewJakubowicz) [reply packages/labs/ssr/src/lib/lit-element-renderer.ts:84]: Brilliant! Is it worth committing some of that excellent comment as a code comment?

**Review by AndrewJakubowicz — DISMISSED** [review]
Thanks for addressing feedback!

File: packages/labs/ssr/src/lib/lit-element-renderer.ts (hunk 2 above)
Comment (augustjk) [reply packages/labs/ssr/src/lib/lit-element-renderer.ts:84]: Although.. along those lines, perhaps `attributeChangedCallback` should already be getting lowercased names instead. Going to consider moving this to the call site of `attributeChangedCallback` instead.

**Comment by augustjk** [comment]
Discussed offline with @AndrewJakubowicz about whether lowercasing all attributes is the right thing to do since SVG elements in the browser are case-sensitive. Marking this as draft while we consider this.

**Comment by augustjk** [comment]
Updated to not modify ssr-dom-shim, just the element renderer. https://github.com/lit/lit/issues/3972#issuecomment-1613816597

File: .changeset/new-news-count.md [hunk 3]
```diff
@@ -0,0 +1,5 @@
+---
+'@lit-labs/ssr': patch
+---
+
+Make attribute handling case-insensitive as it is in the browser.
```
Comment (AndrewJakubowicz) [inline .changeset/new-news-count.md:5]: Nit: Worth updating this changeset to similarly specify "for HTML elements" or something to differentiate from the SVG namespace.

File: packages/labs/ssr/src/test/integration/tests/basic.ts [hunk 4]
```diff
@@ -4825,6 +4825,88 @@ export const tests: {[name: string]: SSRTest} = {
     };
   },
 
+  'LitElement: Attribute binding (mixed case)': () => {
```
Comment (AndrewJakubowicz) [inline packages/labs/ssr/src/test/integration/tests/basic.ts:4828]: Is it possible to add a test case where attribute casing is preserved? E.g. svg element in a render template?

File: .changeset/new-news-count.md (hunk 3 above)
Comment (augustjk) [reply .changeset/new-news-count.md]: Good suggestion!

File: packages/labs/ssr/src/test/integration/tests/basic.ts (hunk 4 above)
Comment (augustjk) [reply packages/labs/ssr/src/test/integration/tests/basic.ts:4828]: I added it separately as a unit test that makes sure the rendered markup has attribute casing preserved. How the browser handles that is up to the browser.

File: packages/labs/ssr/src/test/lib/render-lit_test.ts [hunk 5]
```diff
@@ -360,6 +360,15 @@ for (const global of [emptyVmGlobal, shimmedVmGlobal]) {
...
   });
 
+  test('element with mixed case attributes', async () => {
+    const {render, templateWithMixedCaseAttrs} = await setup();
+    const result = await render(templateWithMixedCaseAttrs('dynamic'));
+    assert.is(
+      result,
+      `<!--lit-part F/N3wW1gNj8=--><!--lit-node 0--><svg dynamicCamel="dynamic" staticCamel="static"></svg><!--/lit-part-->`
+    );
+  });
```
Comment (AndrewJakubowicz) [inline packages/labs/ssr/src/test/lib/render-lit_test.ts:370]: *chefs kiss*

**Review by AndrewJakubowicz — APPROVED** [review]

File: packages/labs/ssr/src/test/integration/tests/basic.ts (hunk 4 above)
Comment (AndrewJakubowicz) [reply packages/labs/ssr/src/test/integration/tests/basic.ts:4828]: What is making you suspect something?

Comment (augustjk) [reply packages/labs/ssr/src/test/integration/tests/basic.ts:4828]: I tried some combinations in the playground and found inconsistent results. I'll investigate and document in a separate issue. :)
